### ISSUE TITLE
[Bug]: not show after click button

### ISSUE THREAD

**Issue by septasite** [marcorombach/livewire-confirm-modal#1]
### What happened?

does not appear after clicking the button, the modal should appear. But the click function that is called directly without going through the confirm-modal. I have followed the instructions to install; is there anything I missed? In the console log, there are no errors appearing.

### How to reproduce the bug

does not appear after clicking the button

### Package Version

0.2.4

### PHP Version

8.2.21

### Laravel Version

11.9

### Which operating systems does with happen with?

macOS

**Comment by marcorombach** [comment]
Hi, thank you for your bug report.
I fixed an issue that prevented the modal to work if no AlpineJS directives like x-data are used elsewhere on the page.

Please try again with version 0.2.5 and let me know if that fixed it for you.

**Comment by septasite** [comment]
Previously, it still didn't work; maybe because I was using manually bundling configuration on Livewire. so I registered the livewire directive after livewire:init and it worked fine.
